Сборка проекта
htmlacademy-adaptive/1837791-cat-energy-24 pull request #12
Opened 2022-01-29 16:37 UTC by Shmal9lka

2022-01-29 18:46 UTC, raccoonroman requested changes

2022-01-29 18:46 UTC, raccoonroman commented on package.json
> +    "gulp-cli": "^2.3.0"
`gulp-cli` в блоке `dependencies` не нужен

2022-01-29 18:46 UTC, raccoonroman commented on source/catalog.html
> +                  <source type="image/webp" media="(min-width: 768px)" srcset="img/catalog-products/catalog-1-tablet.webp 1x, img/catalog-products/catalog-1-tablet@2x.webp 2x" width="161" height="172
```suggestion
                  <source type="image/webp" media="(min-width: 768px)" srcset="img/catalog-products/catalog-1-tablet.webp 1x, img/catalog-products/catalog-1-tablet@2x.webp 2x">
```

2022-01-29 18:46 UTC, raccoonroman commented on source/catalog.html
> +                  <source type="image/webp" media="(min-width: 1440px)" srcset="img/catalog-products/catalog-6-desktop.webp 1x, img/catalog-products/catalog-6-desktop@2x.webp 2x" width="172" height="
```suggestion
                  <source type="image/webp" media="(min-width: 1280px)" srcset="img/catalog-products/catalog-6-desktop.webp 1x, img/catalog-products/catalog-6-desktop@2x.webp 2x" width="172" height="196">
```

2022-01-29 19:27 UTC, Shmal9lka commented on Readme.md
> +* Наставник: [Ирина Малиновская] (https://htmlacademy.ru/profile/irina-malinovskaya).
Извиняюсь. Стыдно

2022-01-30 15:00 UTC, raccoonroman approved these changes

2022-01-30 15:02 UTC, raccoonroman commented on package.json
> +    "gulp-cli": "^2.3.0"
не исправлено. По хорошему это нужно будет исправить

2022-01-30 15:04 UTC, merged