Разметка внутренних страниц
htmlacademy-adaptive/1837791-cat-energy-24 pull request #3
Opened 2021-11-30 16:43 UTC by Shmal9lka

2021-12-04 09:58 UTC, raccoonroman approved these changes
по БЕМ-у все достаточно хорошо :+1:

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +          <article class="catalog__item">
можно сделать чуть более семантично:
`ul.catalog__list > li.catalog__item > article.product-card`

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +          <article class="catalog__item">
во-первых, это список. Во-вторых, article _[представляет самостоятельную часть документа](https://developer.mozilla.org/ru/docs/Web/HTML/Element/article)_, его хорошо бы сделать именно бем-блоком

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +            <a class="catalog__link-img" href="#">
```suggestion
            <a class="catalog__link-img" href="#!">
```

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +              <h3>Cat Energy PRO 500 г</h3>
я бы сделал ссылку внутри заголовка, а не наоборот, так как по умолчанию заголовок - блочный элемент, ссылка - строчный.

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +                <td>Масса</td>
я бы сделал просто списком

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +              <svg width="30" height="30" fill="none" xmlns="http://www.w3.org/2000/svg"><path stroke="#D3D3D3" stroke-width="2" d="M15 0v30M30 15H0"/></svg>
в разметке это лишние атрибуты:
```suggestion
              <svg width="30" height="30" fill="none"><path stroke="#D3D3D3" stroke-width="2" d="M15 0v30M30 15H0"/></svg>
```

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +            <a class="button catalog__button-more" href="#">показать все</a>
```suggestion
            <a class="button catalog__button-more" href="#!">показать все</a>
```

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +          <svg width="78" height="80" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M64.02 34.71H14.03a3.17 3.17 0 0 1-3.18-3.16v-9.47a3.17 3.17 0 0 1 3.18-3.16h49.98a3.17 3.17 0 0 1 3.19 3
не засоряй разметку :)

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +            <a class="social__link" href="#">
```suggestion
            <a class="social__link" href="#!">
```

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +          <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">
```suggestion
          <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive" target="_blank">
```

2021-12-04 09:58 UTC, raccoonroman commented on source/catalog.html
> +            <a class="main-nav__link main-nav__link--current" href="index.html">главная</a>
здесь уже другая ссылка должна быть current

2021-12-04 09:58 UTC, raccoonroman commented on source/form.html
> +            <a class="main-nav__link main-nav__link--current" href="index.html">главная</a>
здесь уже другая ссылка должна быть current, мы на странице формы

2021-12-04 09:58 UTC, raccoonroman commented on source/form.html
> +        <form action="https://echo.htmlacademy.ru" method="post">
здесь для удобства можно добавить target="_blank"

2021-12-04 09:58 UTC, raccoonroman commented on source/form.html
> +                <label class="form__label" for="cat-name">Имя:<sup>*</sup></label>
можно без sup
```suggestion
                <label class="form__label" for="cat-name">Имя:*</label>
```

2021-12-04 09:58 UTC, raccoonroman commented on source/form.html
> +                </label>
можно сделать input, а за ним рядом label, не нужны будут лишние спаны. Кружки можно будет псевдоэлементами сделать https://up.htmlacademy.ru/adaptive/24/criteries#d2

2021-12-04 09:58 UTC, raccoonroman commented on source/form.html
> +                <input class="form__field" type="phone" id="phone" name="phone" placeholder="8 (960) 900-60-90" required>
https://www.w3schools.com/html/html_form_input_types.asp
```suggestion
                <input class="form__field" type="tel" id="phone" name="phone" placeholder="8 (960) 900-60-90" required>
```

2021-12-04 09:58 UTC, raccoonroman commented on source/form.html
> +            <textarea class="form__comment" name="comment" id="comment" cols="30" rows="10">Расскажите обо всех повадках кота</textarea>
"Расскажите обо всех повадках кота" лучше тоже делать через placeholder

2021-12-04 09:58 UTC, raccoonroman commented on source/form.html
> +            <legend class="form__legend"></legend>
```suggestion
            <legend class="form__legend">Дополнительно</legend>
```

2021-12-04 09:58 UTC, raccoonroman commented on source/form.html
> +                </label>
точно так же, можно инпут, а за ним лейбл, без спанов

2021-12-04 09:58 UTC, raccoonroman commented on source/form.html
> +          <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">
на всех страницах нужно поправить футер согласно замечаний по главной странице

2021-12-05 15:37 UTC, Shmal9lka commented on source/form.html
> +                </label>
На предыдущем курсе делали пустым спаном, в демонстрации барбершопа также было, на странице каталога.

2021-12-05 15:41 UTC, Shmal9lka commented on source/form.html
> +                </label>
Прошу разрешить оставить

2021-12-05 20:35 UTC, raccoonroman requested changes

2021-12-05 20:35 UTC, raccoonroman commented on source/catalog.html
> +            <a class="main-nav__link main-nav__link--current" href="index.html">главная</a>
по прежнему не исправлено. Мы находимся на странице каталога, соответственно, класс main-nav__link--current должен быть у другой ссылки

2021-12-05 20:35 UTC, raccoonroman commented on source/catalog.html
> +          <article class="catalog__item">
не исправлено

2021-12-05 20:35 UTC, raccoonroman commented on source/catalog.html
> +              <h3>Cat Energy PRO 500 г</h3>
добавить ссылку внутрь заголовка, а не наоборот

2021-12-05 20:35 UTC, raccoonroman commented on source/catalog.html
> +            <a class="catalog__link-img" href="#">
```suggestion
            <a class="catalog__link-img" href="#!">
```

2021-12-05 20:35 UTC, raccoonroman commented on source/catalog.html
> +          <svg width="78" height="80" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M64.02 34.71H14.03a3.17 3.17 0 0 1-3.18-3.16v-9.47a3.17 3.17 0 0 1 3.18-3.16h49.98a3.17 3.17 0 0 1 3.19 3
код иконки так и не убран со страницы

2021-12-05 20:35 UTC, raccoonroman commented on source/catalog.html
> +          <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">
target="_blank" так и не добавлено

2021-12-06 16:54 UTC, raccoonroman approved these changes
Задание принимаю, замечания что остались, нужно исправить уже в следующем задании

2021-12-06 16:54 UTC, raccoonroman commented on source/catalog.html
> +            <a class="catalog__link-img" href="#!">
соблюдай вложеность. У ссылки отступ слева уже должен быть на два пробела больше.

2021-12-06 16:54 UTC, raccoonroman commented on source/form.html
> +                <label class="form__label" for="cat-name">Имя:<sub>*</sub></label>
повторяю замечание, sub лишний
```suggestion
                <label class="form__label" for="cat-name">Имя:*</label>
```

2021-12-06 16:54 UTC, merged