Стилизация страниц
htmlacademy-adaptive/1837791-cat-energy-24 pull request #5
Opened 2021-12-12 06:30 UTC by Shmal9lka

2021-12-13 00:12 UTC, raccoonroman requested changes
https://htmlacademy-adaptive.github.io/1837791-cat-energy-24/5/
в консоли не должно быть ошибок https://htmlacademy-adaptive.github.io/1837791-cat-energy-24/5/

2021-12-13 00:12 UTC, raccoonroman commented on source/less/components/form.less
> +  flex-direction: row;
стили, которые по-умолчанию, не нужно писать

2021-12-13 00:12 UTC, raccoonroman commented on source/less/components/form.less
> +  & small {
```suggestion
  small {
```

2021-12-13 00:12 UTC, raccoonroman commented on source/less/components/hero.less
> +    url("../../img/index-background.png") top center no-repeat;
вытаскиваешь с фигмы зеленую картинку, в jpg-формате, градиент убираешь, блоку - зеленый фоновый цвет под место картинки

2021-12-13 00:12 UTC, raccoonroman commented on source/less/components/main-nav.less
> +  width: 320px;
```suggestion
  width: 100%;
```

2021-12-13 00:12 UTC, raccoonroman commented on source/less/components/main-nav.less
> +  flex-direction: column;
лишние стили, не вижу смысла использовать флексы

2021-12-13 00:12 UTC, raccoonroman commented on source/less/components/page-footer.less
> +  flex-direction: column;
лишние стили, не вижу смысла использовать флексы

2021-12-13 00:12 UTC, raccoonroman commented on source/less/style.less
> +@import "./components/page-header.less";
если я не ошибаюсь, можно писать без разширения файла:
```suggestion
@import "./components/page-header";
```

2021-12-13 16:35 UTC, Shmal9lka commented on source/index.html
> +              <button class="select__button" type="button">было</button>
Не знаю почему...

2021-12-13 16:55 UTC, Shmal9lka commented on source/less/components/additional.less
> +  list-style-type: none;
увидел в интернетах как частый миксин)

2021-12-13 17:14 UTC, Shmal9lka commented on source/less/components/additional.less
> +  width: 170px;
решил убрать ширину вовсе, с правильными переносами переполнение будет проходить

2021-12-13 17:27 UTC, Shmal9lka commented on source/less/components/control.less
> +.control-label {
таким образом?

2021-12-14 22:11 UTC, raccoonroman requested changes
https://htmlacademy-adaptive.github.io/1837791-cat-energy-24/5/ ошибки в консоли так и не исправлены

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/example.less
> +  font-family: "Oswald", sans-serif;
веб-безопасный шрифт упущен

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/form.less
> +  width: 280px;
ширину убрать

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/form.less
> +  width: 280px;
ширину убрать, либо прописать `100%` если нужно

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/hero.less
> +  width: 100%;
лишние стили

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/hero.less
> +  font-family: "Oswald", sans-serif;
веб-безопасный шрифт упущен

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/hero.less
> +  width: 280px;
ширину убрать

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/main-nav.less
> +  flex-direction: column;
лишие стили не убраны

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/page-footer.less
> +  width: 280px;
ширину убрать

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/page-header.less
> +  width: 280px;
ширину убрать

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/programs.less
> +  width: 100%;
ширину убрать

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/programs.less
> +  width: 280px;
ширину убрать

2021-12-14 22:11 UTC, raccoonroman commented on source/less/components/programs.less
> +  font-family: "Oswald", "Arial", sans-serif;
`"Oswald", "Arial", sans-serif` можно в переменную вынести по желанию

2021-12-14 22:11 UTC, raccoonroman commented on source/less/global/container.less
> +  margin: 0 auto;
а вот здесь уже ширину эту нужно прописать `width: 280px`. Это при условии, если мы решили сетку делать фиксированную а не резиновую

2021-12-14 22:11 UTC, raccoonroman commented on source/less/global/mixins.less
> +  padding: 0;
и добавь margin: 0

2021-12-15 16:31 UTC, Shmal9lka commented on source/less/components/main-nav.less
> +  flex-direction: column;
убрал

2021-12-15 16:46 UTC, Shmal9lka commented on source/form.html
> +      <section class="form container">
понял

2021-12-15 16:48 UTC, Shmal9lka commented on source/index.html
> +      <section class="advantages container">
Понял, принял)

2021-12-15 16:51 UTC, Shmal9lka commented on source/less/components/button.less
> +    color: rgba(255, 255, 255, 0.3);
не знал такого)) буду использовать в будущем

2021-12-15 16:54 UTC, Shmal9lka commented on source/less/components/example.less
> +  width: 280px;
сложно это уяснить сразу, придется привыкать

2021-12-15 16:58 UTC, Shmal9lka commented on source/less/global/container.less
> +  margin: 0 auto;
Пока 280 оставлю

2021-12-15 21:22 UTC, raccoonroman requested changes
https://htmlacademy-adaptive.github.io/1837791-cat-energy-24/5/ ошибки в консоли так и не исправлены. В реальной жизни придется с этим столкнуться и нужно будет что-то делать. Там проблема с путями, любые внешние файлы, которые подлючены через css ,не подключаються. Нужно прописать правильные пути. Если самому не получится исправить, предлагаю созвониться.

2021-12-15 21:22 UTC, raccoonroman commented on source/catalog.html
> +            <li class="catalog__item container">
```suggestion
            <li class="catalog__item">
```

2021-12-15 21:22 UTC, raccoonroman commented on source/catalog.html
> +            <li class="catalog__item container">
контейнер в контейнер не нужно вкладывать

2021-12-15 21:22 UTC, raccoonroman commented on source/catalog.html
> +              <a class="catalog__link-img" href="#!">
карточки товаров самодостаточны, их вполне можно сделать бем-блоком. И я уже об этом говорил
```suggestion
              <article class="product-card">
              <a class="product-card__link-img" href="#!">
```

2021-12-15 21:22 UTC, raccoonroman commented on source/catalog.html
> +              <table class="catalog__details">
```suggestion
                <a class="product-card__link" href="#!">Cat Energy PRO 500 г</a>
              </h3>
              <table class="product-card__details">
```

2021-12-15 21:22 UTC, raccoonroman commented on source/catalog.html
> +                <svg width="30" height="30" fill="none"><path stroke="#!D3D3D3" stroke-width="2" d="M15 0v30M30 15H0"/></svg>
```suggestion
                <svg width="30" height="30" fill="none"><path stroke="#D3D3D3" stroke-width="2" d="M15 0v30M30 15H0"/></svg>
```

2021-12-15 21:22 UTC, raccoonroman commented on source/index.html
> +              <svg width="22" height="22" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M16.5 1.83h-2.75c-1.22 0-2.38.48-3.24 1.32a4.45 4.45 0 0 0-1.34 3.18v2.7H6.42v3.59h2.75v7.19h3.66v-7.
можно убрать лишние атрибуты в разметке
```suggestion
              <svg width="22" height="22" fill="none"><path d="M16.5 1.83h-2.75c-1.22 0-2.38.48-3.24 1.32a4.45 4.45 0 0 0-1.34 3.18v2.7H6.42v3.59h2.75v7.19h3.66v-7.2h2.75l.92-3.59h-3.67v-2.7c0-.23.1-.46.27-.63.17-.17.4-.26.65-.26h2.75v-3.6Z" stroke="#!666" stroke-width="1.1" stroke-linecap="round" stroke-linejoin="round"/></svg>
```

2021-12-15 21:22 UTC, raccoonroman commented on source/less/components/additional.less
> +  min-width: 280px;
убрать, это лишее

2021-12-15 21:22 UTC, raccoonroman commented on source/less/components/additional.less
> +  .font(16px, 16px);
вообще любые миксины лучше ложить в самом начале селектора. Это общепринятая практика. Хорошо настроенный stylelint такое не пропустит

2021-12-15 21:22 UTC, raccoonroman commented on source/less/components/form.less
> +  font-family: "Oswald", "Arial", sans-serif;
если вынес в переменную название шрифта, то используй ее везде

2021-12-15 21:22 UTC, raccoonroman commented on source/less/global/variables.less
> +@oswald-font:"Oswald", "Arial", sans-serif;
```suggestion
@oswald-font: "Oswald", "Arial", sans-serif;
```

2021-12-16 22:57 UTC, raccoonroman requested changes
Не все замечания исправлены. Проблема с путями так и осталась. Я не могу дальше это пропустить :(

2021-12-16 22:57 UTC, raccoonroman commented on source/catalog.html
> +            <li class="catalog__item container">
не убрано
```suggestion
            <li class="catalog__item">
```

2021-12-16 22:57 UTC, raccoonroman commented on source/catalog.html
> +            <li class="catalog__item container">
```suggestion
            <li class="catalog__item">
```

2021-12-16 22:57 UTC, raccoonroman commented on source/less/components/additional.less
> +  min-width: 280px;
не убрано

2021-12-16 22:57 UTC, raccoonroman commented on source/less/components/form.less
> +  font-family: "Oswald", "Arial", sans-serif;
не исправлено

2021-12-18 21:12 UTC, raccoonroman approved these changes
огонь! :+1:

2021-12-18 21:12 UTC, merged