Адаптивная сетка для главной страницы
htmlacademy-adaptive/1837791-cat-energy-24 pull request #6
Opened 2021-12-20 15:20 UTC by Shmal9lka

2021-12-20 23:03 UTC, raccoonroman requested changes
В целом есть даже моменты которые меня порадовали. Там где что-то не так - написал. Жду испавлений ;)

2021-12-20 23:03 UTC, raccoonroman commented on source/less/global/container.less
> +    width: 1220px;
ширина гуд, но саму переменную @desktop-width поменяй на 1300px например. Или 1280

2021-12-21 16:27 UTC, Shmal9lka commented on source/index.html
> +              <img src="../img/leaf-icon.svg" width="60" height="60">
С путями опять засада. Исправил. Но я тут не просто изменял путь. Я сделал нормальные иконки, без лишних элементов в виде зеленых квадратов.

2021-12-21 16:43 UTC, Shmal9lka commented on source/less/components/contacts.less
> +    width: 708px;
удалю пока)

2021-12-21 17:25 UTC, Shmal9lka commented on source/less/components/example.less
> +    background: linear-gradient(to bottom, #ffffff 400px, @bg-color 400px);
направление градиента изменил. Но вот числа изменил

2021-12-21 17:41 UTC, Shmal9lka commented on source/less/components/contacts.less
> +    left: 7.64%;
получилось)

2021-12-21 17:43 UTC, Shmal9lka commented on source/less/components/contacts.less
> +  @media (min-width: @desktop-width) {
1200 сделал. На всякий

2021-12-21 17:55 UTC, Shmal9lka commented on source/less/components/hero.less
> +    box-sizing: border-box;
глобально - в body)

2021-12-21 18:08 UTC, Shmal9lka commented on source/less/components/hero.less
> +    margin-top: 49px;
Исправил

2021-12-21 18:32 UTC, Shmal9lka commented on source/less/components/programs.less
> +    flex-wrap: wrap;
прошу оставить, тут всего два элемента

2021-12-21 20:40 UTC, raccoonroman commented on source/index.html
> +              <img src="../img/leaf-icon.svg" width="60" height="60">
зеленые квадраты легко стилями делаются

2021-12-21 20:42 UTC, raccoonroman commented on source/less/components/example.less
> +    background: linear-gradient(to bottom, #ffffff 400px, @bg-color 400px);
запиши, можем как-нибудь на консультации разобрать

2021-12-21 20:45 UTC, raccoonroman commented on source/less/components/programs.less
> +    flex-wrap: wrap;
а если будет больше? Наверняка другие наставники будут проверять на переполнение бОльшим кол-вом элементов. Может быть 4 спокойно, гриды с таким справятся. А с флексами будет по сложнее чуть

2021-12-21 21:08 UTC, raccoonroman approved these changes
Задание принимаю, те замечания, что я оставил, не критичные, исправишь в ветке следующего задания

2021-12-21 21:08 UTC, raccoonroman commented on source/less/global/global.less
> +  box-sizing: border-box;
свойство box-sizing не наследуюется для дочерних элементов. Ты прописал для body, это все равно, что ничего не прописал) Нужно прописать для всех элементов. Да, сетка может "поплыть", но лучше сделать это сейчас, а не потом.

2021-12-21 21:09 UTC, merged