Адаптивная сетка внутренних страниц
htmlacademy-adaptive/1837791-cat-energy-24 pull request #7
Opened 2021-12-23 14:43 UTC by Shmal9lka

2021-12-24 17:41 UTC, raccoonroman requested changes
В целом все гуд :+1: Замечаний совсем капулечка

2021-12-24 17:41 UTC, raccoonroman commented on source/catalog.html
> +                <a class="product-card__more-icon" href="#!">
нарушение БЭМ. Использование бем-елемента без самого бем-блока https://up.htmlacademy.ru/adaptive/24/criteries#b5
в этой лишке используй классы, относящиеся к блоку catalog
```suggestion
              <div class="catalog__more">
                <a class="catalog__more-icon" href="#!">
```

2021-12-24 17:41 UTC, raccoonroman commented on source/form.html
> +    <header class="page-header page-header--inner container">
может быть имеет смысл сделать модификатор наоборот - для главной страницы. Внутренних может быть сколько угодно, а главная - одна. Пример для главной страницы:
```suggestion
    <header class="page-header page-header--home container">
```

2021-12-24 17:41 UTC, raccoonroman commented on source/less/components/additional.less
> +    grid-column: ~"1/-1";
такого формата я еще не видел. Можешь скинуть ссылку где так пишут. Я видел только так:
```suggestion
    grid-column: 1/-1;
```
наверное, это какое-то костыльное решение для less-препроцесора...

2021-12-24 17:41 UTC, raccoonroman commented on source/less/components/form.less
> +    grid-template-columns: repeat(2, 570px);
```suggestion
    grid-template-columns: repeat(2, 1fr);
```

2021-12-24 17:41 UTC, raccoonroman commented on source/less/components/product-card.less
> +  width: 280px;
ширину не нужно писать

2021-12-26 11:20 UTC, Shmal9lka commented on source/less/components/additional.less
> +    grid-column: ~"1/-1";
Плохих советов послушал. Спрашивал у других как реализовать такую функцию

2021-12-27 11:57 UTC, raccoonroman approved these changes

2021-12-27 11:58 UTC, merged