Module5 task1
htmlacademy-adaptive/1837791-cat-energy-24 pull request #8
Opened 2021-12-30 17:39 UTC by Shmal9lka

2021-12-31 13:43 UTC, raccoonroman requested changes
сложно понять что к чему, когда стили здесь не подключены. Проверь пути, чтобы все отображалось https://htmlacademy-adaptive.github.io/1837791-cat-energy-24/8/
![Screenshot from 2021-12-31 15-43-20](https://user-images.githubusercontent.com/34542700/147826297-d9720632-9a18-4e39-abe6-10d82113fe0e.png)

2021-12-31 13:43 UTC, raccoonroman commented on source/catalog.html
> +        <div class="page-footer__logo--wrapper">
нельзя использовать модификатор без самого бем-блока или бем-элемента

2021-12-31 13:43 UTC, raccoonroman commented on source/less/style.less
> +@import "./components/copyright.less";
```suggestion
@import "./components/copyright";
```

2021-12-31 13:43 UTC, raccoonroman commented on source/index.html
> +                <span class="programs__arrow">
абзац внутри ссылки лишний.

2021-12-31 13:43 UTC, raccoonroman commented on source/index.html
> +              <div class="programs__mark programs__mark--slim"></div>
зачем этот див? выглядит как лишний тег. Если он рисует зеленый круг - то это делается псевдоэлементом

2021-12-31 13:43 UTC, raccoonroman commented on source/index.html
> +              <div class="range-slider__range example_range-slider">
```suggestion
              <div class="range-slider__range example__range-slider">
```

2021-12-31 13:43 UTC, raccoonroman commented on source/js/menu.js
> +let navMain = document.querySelector('.main-nav');
если значения переменных не меняются, используй всегда const вместо let
```suggestion
const navButton = document.querySelector('.page-header__toggle');
const navMain = document.querySelector('.main-nav');
```

2021-12-31 13:43 UTC, raccoonroman commented on source/less/components/contacts.less
> +.contacts__address span {
можно же так писать
```
.contacts__address {
  ...стили...
  span {
    ..стили..
  }
}
```

2022-01-08 08:36 UTC, Shmal9lka commented on source/less/components/contacts.less
> +.contacts__address span {
похоже, что вложенность в медиазапросы работает....

2022-01-08 08:40 UTC, Shmal9lka commented on source/catalog.html
> +        <div class="page-footer__logo--wrapper">
так должно быть по правилам:
page-footer__logo--wrapper заменил на page-footer__logo-wrapper

2022-01-08 09:28 UTC, Shmal9lka commented on source/index.html
> +              <div class="programs__mark programs__mark--slim"></div>
Пришлось отказываться от растровой картинки и переводить в вектор.
из разметки тег img по какой-то причине не удалился.
К тегу привязана сама картинка с изменением размера по медиазапросу.

2022-01-09 00:10 UTC, raccoonroman approved these changes

2022-01-09 00:10 UTC, raccoonroman commented on source/less/components/programs.less
> +    background: url("../../img/cat-slim.svg") no-repeat;
во всех файлах стилей так должно быть
```suggestion
    background: url("../img/cat-slim.svg") no-repeat;
```

2022-01-09 00:10 UTC, raccoonroman commented on source/less/components/programs.less
> +  background: url("./img/arrow.svg") center no-repeat;
```suggestion
  background: url("../img/arrow.svg") center no-repeat;
```

2022-01-09 00:10 UTC, raccoonroman commented on source/less/global/variables.less
> +@tablet-width-only: 1199px;
такс, если @desktop-width: 1280px; то @tablet-width-only будет до 1280px - 1px = 1279px

2022-01-09 00:10 UTC, merged

2022-01-14 12:26 UTC, Shmal9lka commented on source/less/components/example.less
> +  left: 17px;
гениально!

2022-01-14 12:33 UTC, Shmal9lka commented on source/less/components/hero.less
> +    height: 499px;
Надеюсь, что правильно сделал. У меня и так пропорции были не те)

2022-01-14 12:48 UTC, Shmal9lka commented on source/less/components/example.less
> +    background: linear-gradient(to bottom, #ffffff 25%, #f2f2f2 25%);
у меня не удалось нормально отцентровать, линия перехода постоянно скачет. если снизу начинать то подобного не происходит