Декоративные элементы внутренних страниц
htmlacademy-adaptive/1837791-cat-energy-24 pull request #9
Opened 2022-01-16 10:51 UTC by Shmal9lka

Не знаю по какой причине main налезает на header. Но остальное готово!

2022-01-16 15:28 UTC, raccoonroman requested changes

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/contacts.less
> +.contacts__map-icon { //приклеил метку примерно в нужное место
а если карту поводить туда-сюда? Метка должна быть прикреплена к конкретной точке на карте

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/control.less
> +  box-sizing: border-box;
вынес бы это глобально, еще раз говорю. Не нужно будет прописывать каждый раз, один раз прописал и все.

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/form.less
> +    width: 1220px;
убрать

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/form.less
> +    padding-right: 240px;
лучше один раз прописать max-width, чем переопределять padding-right

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/form.less
> +  font-family: "Oswald", sans-serif;
веб-безопасный шрифт не прописан. И есть же переменная вроде как

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/form.less
> +    top: 17px;
по вертикали иконки находятся по центру, используй top: 50%; + transform

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/form.less
> +  fill: @element-basic-color;
`fill` лишний

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/additional.less
> +    top: 14px;
используй top: 50% + transform

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/form.less
> +  font-family: "Oswald", sans-serif;
используй переменную

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/form.less
> +  width: 87.5%;
ширина textarea должна быть 100% на любой ширине экрана

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/form.less
> +    width: 1220px;
убрать

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/form.less
> +  width: 87.5%;
```suggestion
  width: 100%;
```

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/hero.less
> +    object-fit: contain;
уже для `@tablet-width` было прописано, еще раз писать не нужно
```suggestion
```

2022-01-16 15:28 UTC, raccoonroman commented on source/less/components/product-card.less
> +    margin: 0 20px 0;
product-card - это бем-блок, у него не должно быть внешних оступов

2022-01-18 15:18 UTC, Shmal9lka commented on source/less/components/additional.less
> +    width: 267px;
Такой вариант?

2022-01-18 15:19 UTC, Shmal9lka commented on source/less/components/additional.less
> +    width: 1220px;
попытался в резиновую верстку

2022-01-18 15:43 UTC, Shmal9lka commented on source/less/components/catalog.less
> +    width: 1220px;
убрал

2022-01-18 16:10 UTC, Shmal9lka commented on source/less/components/contacts.less
> +.contacts__map-icon { //приклеил метку примерно в нужное место
наверно так надо. На гугле добавил метку и поделился картой. Но окно отображения выглядит не так

2022-01-18 16:26 UTC, Shmal9lka commented on source/less/components/form.less
> +    top: 17px;
правильно?

2022-01-19 03:27 UTC, Shmal9lka commented on source/less/components/additional.less
> +    width: 267px;
Делал часа 4, думал о вариантах. Пришел к такому решению. Нет сил больше решать

2022-01-19 03:34 UTC, Shmal9lka commented on source/less/components/additional.less
> +    width: 1220px;
на остальных вьюпортах я марджины задавал ведь

2022-01-19 03:49 UTC, Shmal9lka commented on source/less/components/form.less
> +    width: 1220px;
я на других вьюпортах в резиновую верстку старался, на этом моменте уже времени не хватило

2022-01-19 04:07 UTC, Shmal9lka commented on source/less/components/form.less
> +  width: 87.5%;
не могу понять как это сделать...
textarea становится слишком широкой

2022-01-19 04:18 UTC, Shmal9lka commented on source/less/components/form.less
> +    width: 1220px;
если убрать то все развалится...я хотел в резиновую верстку на предыдущих вьюпортах

2022-01-19 22:06 UTC, raccoonroman commented on source/less/components/additional.less
> +    width: 267px;
есть же наставник, который может подсказать :)

2022-01-19 22:11 UTC, raccoonroman commented on source/less/components/form.less
> +    top: 17px;
ну давай как-нибудь обсудим этот момент

2022-01-23 15:06 UTC, raccoonroman requested changes

2022-01-23 15:06 UTC, raccoonroman commented on source/less/components/form.less
> +  fill: @element-basic-color;
fill так и не убрал

2022-01-23 15:06 UTC, raccoonroman commented on source/less/components/form.less
> +  fill: #ff8282;
здесь тоже fill убрать

2022-01-23 15:06 UTC, raccoonroman commented on source/less/components/form.less
> +  position: relative;
можно создать бем-блок `title-with-divider` и использовать его во всем проекте, не дублируя стили

2022-01-23 15:06 UTC, raccoonroman commented on source/less/components/form.less
> +    width: 1220px;
1220px все-таки нужно убрать

2022-01-24 14:41 UTC, Shmal9lka commented on source/form.html
> +        <h2 class="form__title desktop-container">Подбор программы</h2>
Заменил.
Ввел элемент и его модификатор

2022-01-24 14:42 UTC, Shmal9lka commented on source/less/global/global.less
> +  box-sizing: border-box;
ничего не развалилось. Удалил

2022-01-24 14:46 UTC, Shmal9lka commented on source/form.html
> +            <div class="form__legend--wrapper">
сделал его элементом

2022-01-24 14:49 UTC, Shmal9lka commented on source/form.html
> +                <svg class="social__icon--facebook" width="22" height="22" viewbox="0 0 22 22" fill="none"><path d="M16.5 1.83h-2.75c-1.22 0-2.38.48-3.24 1.32a4.45 4.45 0 0 0-1.34 3.18v2.7H6.42v3.59h
добавил элемент

2022-01-24 15:49 UTC, Shmal9lka commented on source/less/components/form.less
> +  position: relative;
green-stripe-title сделал, более понятно

2022-01-25 09:13 UTC, raccoonroman requested changes

2022-01-25 09:13 UTC, raccoonroman commented on source/form.html
> +            <div class="form__group--wrapper container__desktop-only">
нарушение БЕМ: использование модификатора без самого бем-блока или бем-элемента, который он модифицирует

2022-01-25 09:13 UTC, raccoonroman commented on source/catalog.html
> +                <svg class="social__icon--vk" width="23" height="16" viewbox="0 0 23 16" fill="none"><path d="M.07 4c0-.63.42-.96 1.27-1.01L4.6 3c.22 0 .37.09.44.27.33.91.7 1.7 1.13 2.37.41.66.95 1.4
не исправлено: использование модификатора без самого бем-блока или бем-элемента, который он модифицирует

2022-01-25 13:31 UTC, Shmal9lka commented on source/catalog.html
> +                <svg class="social__icon--instagram" width="16" height="16" viewbox="0 0 16 16" fill="none"><path d="M7.98.06c1.34 0 2.43.02 3.27.05a6 6 0 0 1 1.92.37 3.99 3.99 0 0 1 2.31 2.32 6 6 0
ввел элементы, модификаторы убрал

2022-01-25 13:32 UTC, Shmal9lka commented on source/index.html
> +        <div class="hero__wrapper container__normal">
исправлено

2022-01-25 14:06 UTC, raccoonroman requested changes

2022-01-25 14:06 UTC, raccoonroman commented on source/catalog.html
> +                <a class="button catalog__button--more" href="#!">показать все</a>
`catalog__button--more` Нарушение БЕМ: Использование модификатора без блока или элемента, который он модифицирует

2022-01-25 14:20 UTC, raccoonroman approved these changes

2022-01-25 14:33 UTC, merged